apiVersion: v1
data:
  ANDROID_APP_URL: https://play.google.com/store/apps/details?id=ai.arislab.arislive
  API_HOST: api
  API_PORT: "1780"
  API_URL: https://beta.arislab.ai/api/
  AUTH0_CLIENT_ID: 6XmLzLa5uAUb44VQeALbBcOyFlHZf3CN
  AUTH0_CLIENT_SECRET: ADW2KScxB32-WbEkF5TpTtfU7qP4XEGl7qdi7gbsLD6JaCCQEQwY7kfD09v7VxG-QZoDcjL-CLdf
  AUTH0_DOMAIN: arislab.auth0.com
  AUTH0_SAML_IDP_CERT_FILE: arislab.pem
  BULKSMS_PASSWORD: 3edcCDE#
  BULKSMS_URL: https://api.bulksms.com/v1/messages
  BULKSMS_USERNAME: nattaponk
  CHATBOT_OUT_OF_STOCK_MESSAGE: "ขออภัยค่ะ สินค้าที่ต้องการชำระเงินหมดพอดีเลยค่ะ \U0001F605"
  CHATBOT_PRODUCT_OUT_OF_BOOKING_MESSAGE: ขออภัยค่ะ คุณไม่ได้ชำระค่าสินค้าภายในระยะเวลาที่กำหนด กรุณากดสั่งซื้อสินค้าใหม่อีกครั้งนะคะ
  CALCULATE_STORE_PACKAGE_URL: https://manage.arislab.ai/calculateStorePackage
  DEFAULT_GB_PAY_TOKEN: yrFKx7r0eZTfEQKJUdRunZTtKOAXthFLZQ4ds0AdDSZpDMQaSEw9mw2+EyYn9FsgZm3gwvrlgMq5KRl0l5Rw/p40fbZ10rkUYkrFDJT3lg81LtfcpgL0gVbuU0mqc10L2ErhxSZrHqYgY8SCRWFTou03yoDKkaKZxlpdPM7XdblRfQLT
  DOMAIN_ALLOW_ORIGIN: "*"
  ENABLE_NOTIFICATION: "true"
  FACEBOOK_APP_SECRET: 73fc7474f3879738ac173d845c473930
  GB_PAY_ADMIN_ARISLAB_ACCOUNT_PUBLIC_KEY: eG4ue6BHyLT6YxgtYISdIadzSu7G61Ns
  GB_PAY_ADMIN_ARISLAB_ACCOUNT_SECRET_KEY: hRsWqup2Z0WkarOu45QJqUuQsaglCgDL
  GB_PAY_ADMIN_ARISLAB_ACCOUNT_TOKEN: AWN1mGuLXY7A3FD3OWL9MAVmKzY0oP8MCaO7C3iEK03QgvKwL+GlPn1Kkaoqqe/Ep8UFWzUKOa0feq+909lxm+MdpPYHrWh5XlC/NIe28/FMOtCkpG7g+WBRFB3sARN1nZUGOjiny0FHlA8AYM8PQ2s/Bydi3RzTlgJ9IphUs98CsN2e
  GB_PAY_AMOUNT_FOR_NO_FEE: "50000"
  TO_GBPAY_EMAIL: it@gbprimepay.com
  GB_PAY_FEE: "20"
  GB_PAY_GATEWAY: https://api.gbprimepay.com/
  GB_PAY_SECRET_KEY: PwpRAVimAIDF7EEe4iLWhh11M8EOaAcz
  INSTANCE_EMAIL: origin@convolab.ai
  INSTANCE_NAME: arislab-prod
  INSTANCE_PASS: 1qazZAQ!
  IOS_APP_URL: https://apps.apple.com/us/app/aris/id1466936667
  IS_SCALE_BOT: "true"
  LINE_NOTIFY_TOKEN: A6TrQ8t1Icin8DvXi8dYVK4qCwk5faNRvySSUQleEnc
  LOG_DESTINATION: rapid7
  RAPID7_LOG_TOKEN: 174097a7-7a98-415f-bae8-e3eb01902d76
  LOG_FILE: ./logs/main.log
  LOG_FOLDER: ../logs
  MEDIA_HOST: media
  MEDIA_PORT: "8000"
  MEDIA_WEB_HOST: media
  MEDIA_WEB_PORT: "4080"
  MSG_PURGE_URL: https://msg.convolab.ai/aris/purge
  MSG_REFRESH_URL: https://msg.convolab.ai/aris/refresh
  MSG_HOST_LIST: http://msg-aws-sea01.convolab.ai,http://hooks.eu-gb.mybluemix.net,https://msg.convolab.ai
  MSG_REFRESH_PATH: aris
  NOTIFICATION_TIME_INTERVAL: "1800"
  PACKAGE_URL: https://manage.arislab.ai/getPlatformPackage?packageName=default
  PAYMENT_RESPONSE_URL: https://beta.arislab.ai/site/payment/checkout/result
  PAYMENT_WEBHOOK_URL: https://beta.arislab.ai/webhook
  PLATFORM_FACEBOOK_APP_ID: "502170539988549"
  PLATFORM_HOST: platform
  PLATFORM_PORT: "3000"
  QUEUESERVICE_HOST: queue-services
  QUEUESERVICE_PORT: "1415"
  RECURRING_BACKGROUND_URL: https://manage.arislab.ai/recurringResult
  RECURRING_PERIOD: "01"
  WITHDRAW_MODE: ON_TIME
  REDIS_HOST: redis
  RVP_PORT: "80"
  RVP_PORT_TLS: "1843"
  SECURESITE_HOST: securesite
  SECURESITE_PORT: "1380"
  SERVER_NAME: PRODUCTION
  SERVICE_STATUS_HOST: localhost
  SERVICE_STATUS_PORT: "1150"
  STREAM_STATUS_HOST: localhost
  STREAM_STATUS_PORT: "1112"
  WEB_PORT: "4080"
  WEB_URL: https://beta.arislab.ai/
  WEBHOOK_HOST: webhook
  WEBHOOK_PORT: "3111"
  XPOWEREDBY: ArisLab
  db_index: arislab-platform
  log: debug
  nes: elastic:FsOUZKwsn82xjCg4t1VJwA73@82910fa177334487bcc84bf9355a7aa3.ap-southeast-1.aws.found.io:9243
  npwd: arislab-platform
  nuser: arislab-platform
  JWT_SECRET_KEY: ArIsLabAkf9kh4af798fJas0G
  EMAI_USER: admin@arislab.ai
  EMAIL_CLIENT_ID: 141545873118-u6vs7jt7bpl8nko9h9ln5s2qm0rkr909.apps.googleusercontent.com
  EMAIL_CLIENT_SECRET: azE9E650HTjadEKJG9tfYpoJ
  EMAIL_REFRESH_TOKEN: 1//04xHmS5fUC7k7CgYIARAAGAQSNwF-L9IrsTa_ZoLqbF81w77imJ9HiDYVK7ppN9lgBHqaDlbJ365WBf_Qc7anhotE5hI5lSRIScw
  ANALYTIC_SERVICE_HOST: localhost
  ANALYTIC_SERVICE_PORT: "3003"
  RAPID7_TOKEN: 4ce91516-f85a-4b81-9168-3a6622c10c29
  AWS_ACCESS_KEY_ID: AKIAJFBWOJPF7E365WHA
  AWS_SECRET_ACCESS_KEY: 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
kind: ConfigMap
metadata:
  namespace: production
  labels:
    io.kompose.service: api-env-configmap
  name: env-configmap
