apiVersion: v1
kind: Service
metadata:
  namespace: alpha
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: queue-services
    app: aris
  name: queue-services
spec:
  type: ClusterIP
  ports:
    - name: "1415"
      port: 1415
      targetPort: 1415
  selector:
    io.kompose.service: queue-services
status:
  loadBalancer: {}
