apiVersion: v1
kind: Service
metadata:
  namespace: alpha
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: webhook
    app: aris
  name: webhook
spec:
  type: ClusterIP
  ports:
    - name: "3111"
      port: 3111
      targetPort: 3111
  selector:
    io.kompose.service: webhook
status:
  loadBalancer: {}
